name: Unit Test

on: [push]
 
jobs:

  run-cases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Run Tests
      run: go test ./... -v
